from generaation import geenerate_description
student_data_struct = {
    'key': 'value'
}

student_data = {   
    #10904040: ["I asked him about his upcoming tests and he said that he has been little busy lately but he feels very confident."],
    #10908436: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10910278: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well." ],
    #10927880: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10930395: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
   #10934656: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10941841: ["I went to his room and asked him what he did for the spring break. He said that he  went home to New York"],
    #10944096: ["I went to his room and asked him what he did for the spring break. He said that he  went to Florida and the beach"],
    #10945999: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10950686: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10951317: ["I met him in the third floor hallway and asked him what he did for the spring break. He said that he went back to his home and shadowed a couple of attorneys as he plans to become a lawyer."],
    #10951688: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
   # 10954314: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10954648: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10955531: [ "I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10956127: ["I went to his room and asked him what he did for the spring break. He said that he  went to Boston "],
    #10957237: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10957262: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10957619: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10957685: ["I went to his room and asked him what he did for the spring break. He said that he went to destin"],
    #10959335: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10959884: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10959945: ["I went to his room and asked him what he did for the spring break. He said that he went to Destin Florida "],
    #10960198: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10960724: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    #10960876: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10960890: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10961040: ["I went to his room and asked him what he did for the spring break. He said that he  went to Destin for the beach "],
    10962441: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10963143: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10963302: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10964074: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10964138: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10966867: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10968321: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10969923: ["I went to his room and asked him what he did for the spring break. He said that he went to destin"],
    10970272: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10970301: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10971731: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10972004: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10972450: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10972588: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10974871: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10975012: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10976578: ["I went to his room and asked him what he did for the spring break. He said that he  went to Houston with his friend"],
    10977700: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10978203: ["I went to his room and asked him what he did for the spring break. He said that he  went to Atlanta"],
    10978380: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10978526: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10978987: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    10981370: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    11028602: ["I met him during the room checks and asked him how he was doing and how his classes were going. He said that everything was going very well."],
    } 
